- hosts: all
  tasks:
    - name: check all host are connected
      ansible.builtin.command:
        cmd: ping -c 1 google.com
- ansible.builtin.import_playbook: ./playbooks/setup.yml
- ansible.builtin.import_playbook: ./playbooks/logging.yml
- ansible.builtin.import_playbook: ./playbooks/wireguard.yml
- ansible.builtin.import_playbook: ./playbooks/adguard.yml
- ansible.builtin.import_playbook: ./playbooks/arrstack.yml
