- hosts: all
  tasks:
    - name: check all host are connected
      ansible.builtin.command:
        cmd: ping -c 1 google.com
- ansible.builtin.import_playbook: setup.yml
- ansible.builtin.import_playbook: logging.yml
- ansible.builtin.import_playbook: wireguard.yml
- ansible.builtin.import_playbook: adguard.yml
- ansible.builtin.import_playbook: arrstack.yml
