- ansible.builtin.import_playbook: setup.yml
- ansible.builtin.import_playbook: logging.yml
- ansible.builtin.import_playbook: wireguard.yml
- ansible.builtin.import_playbook: adguard.yml
- ansible.builtin.import_playbook: arrstack.yml
