- name: install node_exporter and promtail
  hosts: all:!logging
  pre_tasks:
    - name: install packages
      ansible.builtin.dnf:
        name:
          - tar
        state: latest
      become: true
  roles:
    - role: node_exporter
      tags:
        - node_exporter
    - role: promtail
      tags:
        - promtail
      vars:
        promtail_loki_server_url: http://192.168.0.107
        promtail_config_scrape_configs:
        - job_name: journal
          journal:
            json: false
            max_age: 12h
            path: "/run/log/journal/{{ hostvars[inventory_hostname].ansible_machine_id }}/"
            labels:
              job: systemd-journal
          relabel_configs:
          # keep units you care about
          - action: 'keep'
            source_labels: ['__journal__systemd_unit']
            regex: '((^|, )(sshd|vault))+$'
          # make a clean label name without '.service'
          - action: 'replace'
            source_labels: ['__journal__systemd_unit']
            regex: '(.*?)\.service'
            replacement: '\$1'
            target_label: 'unit'

- name: install autounseal vault
  hosts: cluster-autounseal
  roles:
    - role: ansible-community.ansible-vault
      vars:
        vault_listener_localhost_enable: true
        vault_install_hashi_repo: true
        vault_data_path: /opt/vault/data
        vault_harden_file_perms: true
        vault_raft_group_name: cluster-autounseal
        vault_cluster_name: home-lab-autounseal
        vault_datacenter: home-lab
#        vault_tcp_listeners:
#          - vault_address: 0.0.0.0
#            vault_port: 8200
#            vault_tls_disable: true
#            vault_cluster_address: "{{ hostvars[inventory_hostname].ansible_host | ansible.utils.ipv4 }}:8200"
      tags:
        - autounseal
    - role: keepalived
      vars:
        keepalived_virtual_ip: 192.168.0.200
        keepalived_virtual_router: 100
        keepalived_script: true
        keepalived_script_name: check_vault
        keepalived_script_check_command: curl http://{{ hostvars[inventory_hostname].ansible_host | ansible.utils.ipv4 }}:8200/v1/sys/health -f
      tags:
        - keepalived

- name: setup vault for transit
  hosts: "{{ groups['cluster-autounseal'][0] }}"
  roles:
    - role: vault_configure
      vars:
        vault_initialise: true
        vault_unseal: true
        vault_configure_transit: true
        vault_pause_duration: 7
      tags:
        - autounseal

- name: unseal other vaults for clustering
  hosts: cluster-autounseal
  roles:
    - role: vault_configure
      vars:
        vault_initialise: false
        vault_unseal: true
        vault_configure_transit: false
        vault_pause_duration: 7
      tags:
        - autounseal

- name: install vault cluster
  hosts: cluster-main
  pre_tasks:
    - name: get unseal key
      ansible.builtin.command:
        cmd: cat "{{ lookup('ansible.builtin.env', 'HOME') }}"/servers/vault_keys/auto-unseal/unseal_key 
      register: transit_token
      delegate_to: localhost
  roles:
    - role: ansible-community.ansible-vault
      vars:
        vault_listener_localhost_enable: true
        vault_install_hashi_repo: true
        vault_start_pause_seconds: 3
        vault_data_path: /opt/vault/data
        vault_harden_file_perms: true
        vault_raft_group_name: cluster-main
        vault_cluster_name: home-lab-main
        vault_datacenter: home-lab
        vault_transit: true
        vault_transit_tls_skip_verify: true
        vault_transit_address: "http://192.168.0.100:8200" # change to vip later
        vault_transit_token: "{{ transit_token.stdout }}"
#        vault_tcp_listeners:
#          - vault_address: 0.0.0.0
#            vault_port: 8200
#            vault_tls_disable: true
#            vault_cluster_address: "{{ hostvars[inventory_hostname].ansible_host | ansible.utils.ipv4 }}:8200"
      tags:
        - main_cluster
    - role: keepalived
      vars:
        keepalived_virtual_ipaddress: 192.168.0.201
        keepalived_virtual_router: 101
        keepalvied_script: true
        keepalived_script_name: check_vault
        keepalived_script_check_command: curl http://{{ hostvars[inventory_hostname].ansible_host | ansible.utils.ipv4 }}:8200/v1/sys/health -f
      tags:
        - keepalived
- name: setup vault for transit
  hosts: "{{ groups['cluster-main'][0] }}"
  roles:
    - role: vault_configure
      vars:
        vault_initialise: true
        vault_unseal: true
        vault_configure_ssh_certs: true
      tags:
        - ssh_certs

- name: unseal other vaults for clustering
  hosts: cluster-main
  roles:
    - role: vault_configure
      vars:
        vault_initialise: false
        vault_unseal: true
        vault_configure_transit: false\
        vault_pause_duration: 7
      tags:
        - ssh_certs


#- name: install and setup prometheus
#  hosts: prometheus
#  roles:
#  - prometheus.prometheus.prometheus
#  vars:
#    prometheus_targets:
#      node:
#      - targets:
#        - "{{ hostvars['vault'].ansible_host | ansible.utils.ipv4 }}"
#        labels:
#          env: home-lab
#  tags:
#    - prometheus

#- name: setup wireguard
#  hosts: wireguard
#  roles:
#    - role: wireguard
#  tags:
#    - wireguard