- name: promtail
  src: https://github.com/patrickjahns/ansible-role-promtail
  scm: git
- name: node_exporter
  src: https://github.com/geerlingguy/ansible-role-node_exporter
  scm: git
- name: keepalived
  src: https://github.com/Dialgatrainer02/ansible-keepalived.git
  scm: git
