- name: install matrics and log exporters
  hosts: all
  become: true
  roles:
    - role: node_exporter
      tags:
        - node_exporter
    - role: promtail
      tags:
        - promtail
      vars:
        promtail_loki_server_url: "http://{{ hostvars['loki'].ansible_host | ansible.utils.ipv4 }}:3100"
        promtail_config_scrape_configs:
        - job_name: journal
          journal:
            json: false
            max_age: 12h
            path: "/run/log/journal/{{ hostvars[inventory_hostname].ansible_machine_id }}/"
            labels:
              job: "{{ inventory_hostname }}-journal"
          relabel_configs: # todo seperate per instance logging and get nice relabel configs
#          # keep units you care about
#          - action: 'keep'
#            source_labels: ['__journal__systemd_unit']
#            regex: '((^|, )(sshd|vault|wireguard|nginx|))+$'
#          # make a clean label name without '.service'
          - action: 'replace'
            source_labels: ['__journal__systemd_unit']
            regex: '(.*?)\.service'
            target_label: 'unit'
  post_tasks:
    - name: reload promtail
      ansible.builtin.systemd_service:
        name: promtail
        state: restarted
      ignore_errors: true
      tags:
        - promtail

- name: install and setup prometheus
  hosts: prometheus
  roles:
  - prometheus.prometheus.prometheus
  post_tasks:
    - name: add file sd targets
      ansible.builtin.template:
        src: "prometheus/targets.yml.j2"
        dest: "/etc/prometheus/file_sd/node.yml" 
      tags:
        - prometheus
        - service_discovery
  tags:
    - prometheus
- name: install and setup loki
  hosts: loki
  roles:
    - role: loki
  tags:
    - loki
- name: install and setup granfana
  hosts: grafana
  roles:
    - role: grafana.grafana.grafana
  vars:
    grafana_security:
      admin_user: olivia
      admin_password: testing
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://{{ hostvars["prometheus"].ansible_host | ansible.utils.ipv4 }}:9090'
        basicAuth: false
      - name: loki
        type: loki
        access: proxy
        url: 'http://{{ hostvars["loki"].ansible_host | ansible.utils.ipv4 }}:3100'
        basicAuth: false
  tags:
    - grafana