---
# tasks file for ansible-loki
- name: create loki user
  ansible.builtin.user:
    name: loki
    create_home: false
    system: true
    state: present
- name: create loki group
  ansible.builtin.group:
    name: loki
    state: present
- name: install latest  loki release
  ansible.builtin.unarchive:
    src: https://github.com/grafana/loki/releases/latest/download/loki-linux-amd64.zip
    dest: /usr/bin/
    remote_src: yes
- name: create loki config directory
  ansible.builtin.file:
    name: /etc/loki
    state: directory
- name: Download loki config
  ansible.builtin.copy:
    src: loki.yml
    dest: /etc/loki/loki.yml
    mode: '0755'
    owner: root
- name: copy service file
  ansible.builtin.copy:
    src: loki.service
    dest: /etc/systemd/system/loki.service
- name: start loki service
  ansible.builtin.systemd_service:
    name: loki
    state: started
    daemon_reload: true
