---
# tasks file for service_cleanup
- name: get trusted user certs
  ansible.builtin.command:
    cmd: curl $VAULT_ADDR/v1/ssh-client-signer/public_key
  register: trusted_user_ca
  environment:
    VAULT_ADDR: "http://{{ service_cleanup_vault_ip }}:8200"
- name: write trusted user cas to file
  ansible.builtin.copy:
    content: "{{ trusted_user_ca.stdout }}"
    dest: /etc/ssh/trusted-user-ca-keys.pem
    owner: root
    group: root
- name: edit sshd config
  ansible.builtin.copy:
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: '644'
- name: stop sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: stopped
- name: start sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: started
- name: remove staging key
  ansible.builtin.file: 
    path: "{{ item }}" 
    state: absent
  with_fileglob: /etc/ssh/ssh_host*
- name: lock root account
  ansible.builtin.user:
    name: root
    password_lock: true