---
- name: Install and setup adguard
  hosts: adguards
  vars:
    adguardhome_daemon: adguardhome
    adguardhome_bin_file: /usr/local/bin/AdGuardHome
    adguardhome_user: adguardhome
    adguardhome_group: adguardhome
    adguardhome_data_dir: /var/lib/adguardhome
    adguardhome_config_file: /etc/adguardhome/AdGuardHome.yml
    adguardhome_webhost: "{{ hostvars[inventory_hostname].ansible_host | ansible.utils.ipv4 }}"
    adguardhome_dnshosts:
      - "{{ hostvars[inventory_hostname].ansible_host | ansible.utils.ipv4 }}"
      - 127.0.0.1
  roles:
    - role: 0x0i.systemd
      vars:
        unit_config:
          - name: "{{ adguardhome_daemon }}"
            enabled: true
            state: started
            path: /run/systemd/system
            Unit:
              Description: AdGuardHome DNS Server
              ConditionFileIsExecutable: "{{ adguardhome_bin_file }}"
              After: network.target
            Service:
              Type: simple
              Restart: on-failure
              RestartSec: 2s
              TimeoutStopSec: 0
              User: "{{ adguardhome_user }}"
              Group: "{{ adguardhome_group }}"
              WorkingDirectory: "{{ adguardhome_data_dir }}"
              ExecStart: "{{ adguardhome_bin_file }} --config {{ adguardhome_config_file }} --work-dir {{ adguardhome_data_dir }}"
              AmbientCapabilities: CAP_NET_BIND_SERVICE
            Install:
              WantedBy: multi-user.target
    - role: adguard
  tags:
    - adguard
- name: Change all dns servers to point at adguard
  hosts: all:!adguards
  tasks:
    - name: Make pve ignore resolv conf # find way to diffrenciate between lxc and not
      ansible.builtin.file:
        name: /etc/.pve-ignore.resolv
        state: touch
        mode: "0777"
      become: true
    - name: Insert name servers into resolv conf
      ansible.builtin.blockinfile:
        path: /etc/resolv.conf
        append_newline: true
        prepend_newline: true
        insertafter: /%^
        block: |
          nameserver: {{ hostvars['adguard1'].ansible_host | ansible.utils.ipv4 }}
          nameserver: {{ hostvars['adguard1'].ansible_host | ansible.utils.ipv4 }}
      become: true
  tags:
    - dns-servers
    - adguard
