---

- name: Setup Arr stack with Buildarr
  hosts: arrstack
  become: true
  roles:
    - ../roles/arrstack
  tags: 
    - arrstack

#- name: Deploy Media Stack on configured hosts
#  hosts: arrstack
#  become: true
#  pre_tasks:
#    - name: remove podman docker
#      ansible.builtin.dnf:
#        name: 
#          - docker
#          - podman-docker
#          - podman
#        state: absent
#    - name: add docker ce repo
#      ansible.builtin.command:
#        cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
#    - name: update dnf
#      ansible.builtin.dnf:
#        name: "*"
#        state: latest
#    - name: install docker
#      ansible.builtin.dnf:
#        name: 
#          - docker-ce
#        state: latest
#    - name: start docker service
#      ansible.builtin.systemd_service:
#        name: docker
#        state: started
#        enabled: true
#  roles:
#    - buildarr.mediastack.base
##    - buildarr.mediastack.jellyfin
#    - buildarr.mediastack.transmission
#    - buildarr.mediastack.flaresolverr
#    - buildarr.mediastack.sonarr
#    - buildarr.mediastack.radarr
#    - buildarr.mediastack.prowlarr
#    - buildarr.mediastack.jellyseerr
#    - buildarr.mediastack.buildarr