---
- name: Use duckdns for dynamics dns
  hosts: wireguard
  pre_tasks:
    - name: Clear old records
      ansible.builtin.uri:
        url: https://www.duckdns.org/update?domains={{ item }}&token={{ duckdns_token }}&clear=true
        method: GET
      register: result
      loop:
        - dialgatrainer
        - dialgatrainer-staging
        - olivia420
        - oc-1-vps
        - hn-1-prx
      run_once: true
  tasks:
    - name: Update domain for home network
      ansible.builtin.uri:
        url: https://www.duckdns.org/update?domains='hn-1-prx'&token={{ duckdns_token }}
        method: GET
      when: hostvars[inventory_hostname].ansible_host is regex_search("192.168.0.*")
      run_once: true
    - name: Update the outside vps domain
      ansible.builtin.uri:
        url: https://www.duckdns.org/update?domains='oc-1-vps'&token={{ duckdns_token }}
        method: GET
      register: result
      when: inventory_hostname == 'wireguard-oci'
      run_once: true
  tags:
    - duckdns
