- name: install minecraft in docker Compose
  hosts: minecraft
  pre_tasks:
    - name: remove podman docker
      ansible.builtin.dnf:
        name: 
          - docker
          - podman-docker
          - podman
        state: absent
    - name: add docker ce repo
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    - name: update dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: install docker
      ansible.builtin.dnf:
        name: 
          - docker-ce
        state: latest
    - name: start docker service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
  tasks: 
    - name: create minecraft dir
      ansible.builtin.file:
        name: /opt/minecraft
        state: directory
    - name: copy compose file
      ansible.builtin.copy:
        src: ../files/docker-compose-minecraft.yml
        dest: /opt/minecraft/docker-compose.yml
    - name: start doker compose
      community.docker.docker_compose_v2:
        project_name: minecraft_server
        project_src: /opt/minecraft
  tags:
    - minecraft