- name: reset opc password for debugging
  hosts: wireguard-oci
  pre_tasks: 
    - name: reset opc user password
      ansible.builtin.user:
        name: opc
        password: $6$rounds=656000$mysecretsalt$bt4UIMNYnPD6yfAsuQs2.da7EBtjIJCS/GFDNkL6k0VsWKFVFbxhXuugCPrHDbire1lEiBe.5uF4iYeeI1EpJ.
      become: true
  tags:
    - debug

- name: initial setup
  hosts: all:!laptop
  tasks:
    - name: remove firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: absent
      become: true
    - name: install packages
      ansible.builtin.dnf:
        name:
          - tar
          - yum-utils
          - nftables
        state: latest
      become: true
    - name: add nftable rules
      ansible.builtin.template:
        src: ../templates/homelab-ruleset.nft.j2
        dest: /etc/nftables.nft
      become: true
    - name: check nftables is started
      ansible.builtin.systemd_service:
        name: nftables
        state: started
        enabled: true
      become: true
    - name: apply firewall rules
      ansible.builtin.command:
        cmd: nft -f /etc/nftables.nft
      become: true
    - name: system update
      ansible.builtin.dnf:
        name:
          - "*"
        state: latest
      become: true
      tags:
        - update
    - name: check if nodes need rebooting
      ansible.builtin.command:
        cmd: needs-restarting -r
      register: result
      ignore_errors: true
    - name: reboot if needed
      ansible.builtin.reboot:
      become: true
      when: result.rc == 1
    - name: wait for instances to come back online
      ansible.builtin.wait_for_connection:
  tags:
    - setup