- name: initial setup
  hosts: all:!laptop
  tasks:
    - name: remove firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: absent
            become: true
    - name: install packages
      ansible.builtin.dnf:
        name:
          - tar
          - yum-utils
          - nftables
        state: latest
      become: true
    - name: add nftable rules
      ansible.builtin.template:
        src: ../files/homelab-ruleset.nft.j2
        dest: /etc/nfttables.conf #find right path later
    - name: system update
      ansible.builtin.dnf:
        name:
          - "*"
        state: latest
      become: true
      tags:
        - update
    - name: check if nodes need rebooting
      ansible.builtin.command:
        cmd: needs-restarting -r
      register: result
      ignore_errors: true
    - name: reboot if needed
      ansible.builtin.reboot:
      become: true
      when: result.rc == 1
    - name: wait for instances to come back online
      ansible.builtin.wait_for_connection:
  tags:
    - setup