- name: setup wireguard
  hosts: wireguard
  pre_tasks:
    - name: enable ip forwarding
      ansible.builtin.command:
        cmd: sysctl -w net.ipv4.ip_forward=1
      ignore_errors: true
  roles:
    - role: wireguard
  tags:
    - wireguard
  become: true
